name: Logo Request
description: Request a new logo invalid or missing
title: "[Logo Request]: "
labels: ["logo request"]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      options:
        - label: I have searched for existing requests
          required: true
        - label: I strictly followed the Contributing Guidelines
          required: true
  - type: input
    id: name
    attributes:
      label: Brand Name
      description: The name of the brand
      placeholder: e.g. "My Brand"
    validations:
      required: true
  - type: input
    id: website
    attributes:
      label: Website
      description: Official website of the brand
      placeholder: https://example.com
    validations:
      required: true
  - type: textarea
    id: sources
    attributes:
      label: Source Links
      description: Link to official brand assets (press kit, brand guidelines)
      placeholder: https://brand.example.com/assets
    validations:
      required: true
